#!/usr/bin/env bash

if command -v yum > /dev/null
then
    sudo yum -y install ctags cscope vim htop
fi

if command -v apt-get > /dev/null
then
    # Latest stable Git release
    sudo apt-get install python-software-properties
    sudo add-apt-repository ppa:git-core/ppa
    sudo apt-get update
    sudo apt-get install git

    sudo apt-get install ctags cscope vim htop
fi
