#!/usr/bin/env bash

# Mac
function install_deps_mac
{
    # Homebrew
    if ! command -v brew > /dev/null; then
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    fi

    # Apple Silicon
    if [ -d /opt/homebrew ]; then
        eval "$(/opt/homebrew/bin/brew shellenv)"
    fi

    brew doctor
    brew install cscope wget vim git
}

# Fedora
function install_deps_linux_fedora
{
    sudo dnf -y install ctags cscope vim htop git
}

# Ubuntu/Debian
function install_deps_linux_debian
{
    sudo apt-get update
    sudo apt-get install -y ctags cscope vim htop git
}

# Linux
function install_deps_linux
{
    if command -v dnf > /dev/null; then
        install_deps_linux_fedora
    elif command -v apt-get > /dev/null; then
        install_deps_linux_debian
    fi
}

PLATFORM="$(tr '[:upper:]' '[:lower:]' <<< "$(uname)")"

case $PLATFORM in
    "darwin")
        install_deps_mac
        ;;
    "linux")
        install_deps_linux
        ;;
    *)
        echo "No dependencies setup for $PLATFORM"
        ;;
esac
