#!/usr/bin/env bash

show_usage() {
    echo
    echo "Links dotfiles to your $HOME directory"
    echo
    echo "USAGE: $0 [-f] [--force]"
    echo
    echo "  force        Prevents confirmation prompt to override existing files"
    echo

    [ ! -z "$1" ] && exit $1
}

if [ "$1" == "--help" ]; then
    show_usage 64
fi;

if [[ "$1" != "--force" && "$1" != "-f" ]]; then
    echo
    read -p "This may overwrite existing files in your home directory. Are you sure? (Y/n) " -n 1
    echo
    if [[ $REPLY =~ ^[Nn]$ ]]; then
        exit 64
    fi
fi

pushd $(dirname $0) > /dev/null

for file in .*
do
    if [[ "${file}" == "." ]]; then
        continue
    fi

    if [[ "${file}" == ".." ]]; then
        continue
    fi

    if [[ "${file}" == ".git" ]]; then
        continue
    fi

    if [[ "${file}" == ".gitmodules" ]]; then
        continue
    fi

    if [ -e "${file}" ]
    then
        ln -fsv $PWD/${file} $HOME
    fi
done

cp -rfv $PWD/bin $HOME

# Source platform specific profile
UNAME=$(uname)

case $UNAME in
    "")
        ;;
    "Darwin")
        PLATFORM=osx
        ;;
    "CYGWIN"*)
        PLATFORM=windows
        ;;
    "MINGW"*)
        PLATFORM=windows
        ;;
    *)
        PLATFORM="$(tr [A-Z] [a-z] <<< "$UNAME")"
        ;;
esac

if [ -f "$PLATFORM/.$PLATFORM" ]; then
    ln -fsv $PWD/$PLATFORM/.$PLATFORM $HOME
fi

popd > /dev/null